# Generated by Django 5.2.4 on 2025-08-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
